import Head from "next/head";
import Image from "next/image";

export default function Home() {
  return (
    <>
      <Head>
        <title>Iron Wolf Backend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Image src="/adaptive-icon.png" alt="Iron Wolf Logo" fill sizes="100%" style={{ objectFit: "contain", opacity: 0.15, zIndex: 0 }} />
        <h1>Iron Wolf Backend</h1>
        <p>Iron Wolf Fitness Personal Api</p>
        <div>
          <p>
            Please Visit Us to Learn more!{" "}
            <a href="https://ironwolffitness.com/" target="_blank">
              Iron Wolf Fitness
            </a>
          </p>
        </div>
      </main>
    </>
  );
}
