import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Iron Wolf Backend</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Iron Wolf Backend</h1>
        <p>Iron Wolf Fitness Personal Api</p>
        <div>
          <p>
            Please Visit Us to Learn more!{" "}
            <a href="https://ironwolffitness.com/" target="_blank">
              Iron Wolf Fitness
            </a>
          </p>
        </div>
      </main>
    </>
  );
}
